apiVersion: v1
kind: Secret
metadata:
  name: userservice-secret
  labels:
    app: user-service
type: Opaque
data:
  POSTGRES_PASSWORD: MXUtZDgtcHc=
  REDIS_PASSWORD: aERJU0dYKjU3Qmh1JCZ0Iw==
  SECRET_KEY: bDJUXmV3VkMjTEZUQ044eTdq
