apiVersion: v1
kind: ConfigMap
metadata:
  name: userservice-config
data:
  FLASK_ENV: "production"
  FRONTEND_URL: "http://localhost:80"
  DB_HOST: "user-service-db"
  DB_PORT: "5432"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  PORT: "5000"
  POSTGRES_USER: "dev_user"
  POSTGRES_DB: "userservice_db"
