apiVersion: v1
kind: ConfigMap
metadata:
  name: userservice-config
data:
  FLASK_ENV: "production"
  FRONTEND_URL: "http://localhost:3000"
  DB_HOST: "pricing-service-db"
  DB_PORT: "5432"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "user"
  POSTGRES_DB: "crypto_tracker"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  PORT: "5000"
