apiVersion: v1
kind: Secret
metadata:
  name: userservice-secret
type: Opaque
data:
  SECRET_KEY: c2VjcmV0X2tleQ==  # base64 encoded "secret_key"
  POSTGRES_PASSWORD: cGFzc3dvcmQ=  # "password"
  REDIS_PASSWORD: cmVkaXNwYXNz  # "redispass"
