apiVersion: v1
kind: Secret
metadata:
  name: userservice-secret
  labels:
    app: user-service
type: Opaque
data:
  POSTGRES_USER: ZGV2X3VzZXI=           # dev_user
  POSTGRES_PASSWORD: aERJU0dYKjU3Qmh1JCZ0Iw==
  POSTGRES_DB: dXNlcnNlcnZpY2VfZGI=     # userservice_db
  DB_PORT: NTQzMg==                     # 5432
  DB_HOST: dXNlci1zZXJ2aWNlLWRi         # user-service-db (base64)
  REDIS_PASSWORD: aERJU0dYKjU3Qmh1JCZ0Iw==
  REDIS_HOST: cmVkaXM=                  # redis
  REDIS_PORT: NjM3OQ==                  # 6379
  SECRET_KEY: bDJUXmV3VkMjTEZUQ044eTdq
  FRONTEND_URL: aHR0cDovL2xvY2FsaG9zdDo4MA== # http://localhost:80
