apiVersion: v1
kind: ConfigMap
metadata:
  name: userservice-config
data:
  FRONTEND_URL: "http://localhost:3000"
  DB_HOST: "postgresql"
  DB_PORT: "5432"
  POSTGRES_USER: "user"
  POSTGRES_DB: "crypto_tracker"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  PORT: "5000"
